### ISSUE TITLE
I'm not able to install and run this properly unlike other modules that I have used before. 

### ISSUE THREAD

**Issue by itsmkishore** [nearform/node-hidden-markov-model-tf#29]
I'm getting the following error after going through readme file. I'm a newbie with nodejs. So. I might have done something stupid. The module from require function is getting loaded properly too. But I'm not able to figure out the issue. Please help @AndreasMadsen !

/Volumes/Code/code/local/nodefiles/hmm/hmm-test.js:66
await hmm.setParameters({
 ^^^^^

SyntaxError: await is only valid in async function
    at wrapSafe (internal/modules/cjs/loader.js:979:16)
    at Module._compile (internal/modules/cjs/loader.js:1027:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47

**Comment by itsmkishore** [comment]
I figured it out.

**Comment by nurulrsadi** [comment]
Can I know how you fix that? I've some issue like that too
